name: Build release
on:
  release:
    types: [published]
jobs:
  build_release:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
    - name: Write release version
      run: |
        VERSION=${GITHUB_REF_NAME#v}
        echo Version: $VERSION
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Checkout sources
      uses: actions/checkout@v4.2.2
      with:
        ref: ${{ github.head_ref }}
        fetch-depth: 0

    - name: Setup Java
      uses: actions/setup-java@v4.5.0
      with:
        distribution: 'temurin'
        java-version: 23

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4.2.1

    - name: Build
      env:
        ORG_GRADLE_PROJECT_githubActor: ${{ secrets.GITHUBACTOR }}
        ORG_GRADLE_PROJECT_githubToken: ${{ secrets.GITHUBTOKEN }}
        ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_KEY }}
        ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}
        ORG_GRADLE_PROJECT_sonatypeUser: ${{ secrets.SONATYPE_USER }}
        ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.SONATYPE_PASSWORD }}
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      run: ./gradlew -Pversion=$VERSION build sourcesJar dokkaGeneratePublicationHtml publishToSonatype closeAndReleaseSonatypeStagingRepository

    - name: Find branch from tag
      id: find-branch
      env:
        TAG_NAME: ${{ github.event.release.tag_name }}
      run: |
        BRANCH=$(git branch -r --contains $TAG_NAME | grep -v '\->' | sed 's/origin\///' | head -n 1)
        if [ -z "$BRANCH" ]; then
          echo "Branch not found for tag $TAG"
          exit 1
        fi
        echo Branch: $BRANCH
        echo "BRANCH=$BRANCH" >> $GITHUB_ENV

    - name: Checkout branch HEAD
      run: git checkout ${BRANCH}

    - name: Update README
      run: sh .github/scripts/update-readme-version.sh

    - name: Create Pull Request
      uses: stefanzweifel/git-auto-commit-action@v5.0.1
      with:
        commit_message: Dependency version in README.md updated to ${{ env.VERSION }}
        file_pattern: 'README.md'
